plugins {
    id("idea")
    id("org.jetbrains.intellij.platform") version "2.3.0"
    id("org.jetbrains.intellij.platform.migration") version "2.3.0"
}

group "com.github.setial"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity "2024.3.4", false
        bundledPlugin('com.intellij.java')
    }
    implementation 'commons-beanutils:commons-beanutils:1.9.4'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'org.apache.commons:commons-lang3:3.9'
    implementation 'commons-logging:commons-logging:1.2'
    implementation 'org.freemarker:freemarker:2.3.32'
    testImplementation group: 'junit', name: 'junit', version: '4.9'
}

intellijPlatform {
    pluginConfiguration {
        id = "com.github.setial"
        version = "4.1.4"
        name = "JavaDoc"
        vendor {
            name = "Sergey Timofiychuk"
            email = "s.timofiychuk@gmail.com"
            url = "http://tsergey.github.io/intellij-javadocs/"
        }
    }
}